### ISSUE TITLE
Agent's z and h values are ignored

### ISSUE THREAD

**Issue by sskorol** [robotics-upo/hunav_gazebo_wrapper#2]
Hi @noeperez @roberottt,

I use the following agent config for simulation:
```yaml
hunav_loader:
  ros__parameters:
    map: small_house
    publish_people: true
    agents:
      - agent1
    agent1:
      id: 1
      skin: 3
      behavior: 1
      group_id: -1
      max_vel: 1.5
      radius: 0.5
      init_pose:
        x: 1.866144
        y: 0.323669
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: 3.629330
        y: -0.875358
        h: 1.250000
      g1:
        x: 2.938339
        y: -3.290771
        h: 1.250000
      g2:
        x: -0.968620
        y: -3.867865
        h: 1.250000
      g3:
        x: -1.914606
        y: -0.930699
        h: 1.250000
```
The problem I noticed is that the spawned human doesn't touch the floor and just walks in the air.

![flying_model](https://user-images.githubusercontent.com/6638780/202021882-3b405c63-fd0a-438d-9d9f-d52d0ea2ac7c.png)

I tried to set different z and h values. But it doesn't seem to have any effect in Gazebo at all.

Could you please advise what I'm missing here?
